// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFXKO55qqv12KRAP_rUA_oB42hKq7KGTk',
    appId: '1:967848756860:android:783f440418be764506ebf9',
    messagingSenderId: '967848756860',
    projectId: 'food-ordering-app-efbc9',
    databaseURL: 'https://food-ordering-app-efbc9-default-rtdb.firebaseio.com',
    storageBucket: 'food-ordering-app-efbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaurVOMHAUkNrBiLCWLvKZjdnu7O0rI8',
    appId: '1:967848756860:ios:cd79f0ab6a5a00cb06ebf9',
    messagingSenderId: '967848756860',
    projectId: 'food-ordering-app-efbc9',
    databaseURL: 'https://food-ordering-app-efbc9-default-rtdb.firebaseio.com',
    storageBucket: 'food-ordering-app-efbc9.appspot.com',
    androidClientId: '967848756860-j1p7mbcukdeq913fh917c3tfgljdf4u4.apps.googleusercontent.com',
    iosClientId: '967848756860-e0dulj9003u0bd6rl3rg63s2hhh9ugaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
